### ISSUE TITLE
android emulator just hangs

### ISSUE THREAD

**Issue by chovy** [GrayBullet/generator-graybullet-cordova#22]
I'm not sure why this is happening (mac)

I installed android-sdk with brew, everything seems to work fine, I installed API (19) and created a Nexus 6 device (not sure I did this right).

I've tried several combinations, but the app never loads in android when I run `grunt emulate`. It works fine in browser and ios emulator, but android starts, but I just get a black screen. Waiting like 30 minutes one time just to see.

**Comment by masakura** [comment]
Since the Android emulator is problematic, I want you to try the following.

Please run the `grunt emulate`, after start the android emulator.

```
$ emulator -avd your_avd_name &
... after emulator started. (Shown android lock screen)
$ grunt emulate
```

**Comment by chovy** [comment]
That just starts two of them, both just give me a black screen.

**Comment by masakura** [comment]
It seems to boot failed android emulator.

```
$ emulator -avd avd1
```

In my environment, run `emulator -avd avd1` and to wait for about 30 seconds, Android lock screen is displayed.

If the lock screen does not appear in the order of a few minutes, it becomes of Android Emulator problem.

- OS X Yosemite
- Android SDK 24.0.2 full install
- avd1 (Nexus 7 2012/android-19/x86)


If the lock screen displayed, and black screen with `grunt emulate`, I want you to confirm whether cordova to work.

```
$ cordova create project1
$ cd project1
$ cordova platform add android
$ emulator -avd your_avd_name
... wait lock screen shown
$ cordova emulate
```

**Comment by chovy** [comment]
I tried creating an avd like yours, can you tell me what settings you are using?

![screenshot 2015-02-01 23 47 18](https://cloud.githubusercontent.com/assets/27381/5997186/bc733c0a-aa6c-11e4-81fb-3003fa668f6b.png)

I still just get a black screen just by running the emulator w/o going via cordova.

**Comment by masakura** [comment]
armeavi-v7a ABI is very slow! You may install the Intel HAXM Accelerator, and use the x86 ABI.

But it boot a slow. it works. About 5 minutes to wait for the lock screen is displayed.

```
$ android create avd -n avd442 -t android-19 -b armeabi-v7a -d 'Nexus 7'
$ emulator -avd avd442
```

1. Start `ANDROID` boot animation.
2. Wait about 5 minutes.
3. Display android lock screen.

I'm sorry, I think I English is not transmitted well the poor. This comment was translated `Google Translator` from Japanese. You had better refer to the place of the other.

- http://developer.android.com/tools/help/emulator.html
- http://developer.android.com/tools/devices/emulator.html
- http://stackoverflow.com/search?q=android+emulator+black+screen

**Comment by masakura** [comment]
@chovy This Issue is closed. Because, it is not a problem of generator-graybullet-cordova. If I am wrong, please reopen.

I hope that this problem is resolved quickly.
